# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Kenan Klisura
title: kklisura's Blog
email: kklisura@hotmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Personal blog

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kklisura.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kklisura
github_username:  kklisura

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Minima theme navigation items https://github.com/jekyll/minima#customize-navigation-links
header_pages:
  - tags.html
  - about.md
