url: https://kklisura.com
baseurl: "/"

title: Kenan Klisura's Blog
sub-title: Collection of my thoughts on various different things

header_pages:
  - posts.html
  - links.md
  - about.md

exclude:
  - third-party/

sass:
  load_paths:
    - third-party/